### ISSUE TITLE
7.1 Release Checklist

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#1136]
- [x] Verify whats-new (@tgorkin )
- [x] Verify upgrade-guide (@tgorkin )
- [x] Verify all 7.1 issues are closed or move out (@tgorkin )
- [x] Verify all API changes are documented (@Pessimistress )
- [ ] Documentation: Update source file urls to point to 7.1-release branch
- [ ] Website (docs and example) [staging](https://tsherif.github.io/luma.gl/#/)
    - [x] Testing on Chrome (@jianhuang01)
    - [ ] Testing on Safari (@xintongxia)
    - [x] Testing on Firefox (@1chandu) 
    - [x] Testing on Edge + IE11 (@tsherif)
    - [x] Testing on iOS (@Pessimistress)
    - [x] Testing on Android (@Pessimistress)

Testing procedure
- access staged doc website
- go through all examples
- verify functionality in control panels
- look for console errors/warnings
- add results of testing as comments on this issue

**Comment by 1chandu** [comment]
FireFox:

- [ ] Whats New page: We should briefly describe new feature and provide links for docs. Remove detailed explanation/code samples for Shader Injection and Animaiton systems and replace them with links to docs.

- [ ] Missing 7.1 section in Upgrade Guide.

**Comment by tsherif** [comment]
I can simplify the What's New. Do we need an upgrade guide if there aren't breaking changes?

**Comment by 1chandu** [comment]
> Do we need an upgrade guide if there aren't breaking changes?

I see, it seems good then, also previously we didn't specify any if no breaking changes.

**Comment by tgorkin** [comment]
@tsherif To be consistent, the links in the new content of What's New should probably be relative, i.e. point to the docs hosted on the website instead of github markdown.

**Comment by Pessimistress** [comment]
@tsheif @tgorkin if you write the link in the form of `/docs/some/file.md` it will work when browsing source on GitHub, and the website will replacr it with the proper website url at runtime.

**Comment by jianhuang01** [comment]
- [ ] ShaderTools / Using GLSL 3.00 ES page is missing

**Comment by tsherif** [comment]
Edge: ✔️ 

IE:
- [ ] All examples broken except Fragment, Mandelbrot, Quasicrystals, lessons 1-3 (same as before)

**Comment by 1chandu** [comment]
Firefox : 

- [ ] Deprecation warning : `luma: `updateAccessor(...)` is deprecated and will be removed in a later version. Use `setAccessor(new Accessor(buffer.accessor, ...)` instead`
- [ ] Deprecation warning: `luma: `Buffer.size` is deprecated and will be removed in a later version. Use `Buffer.accessor.size` instead`
- [ ] lesson 16: Texture missing on the cube.

**Comment by Pessimistress** [comment]
Mobile:
[ ] glTF example is not interactive
