### ISSUE TITLE
7.2 Release Checklist

### ISSUE THREAD

**Issue by tgorkin** [uber/luma.gl#1190]
- [x] Verify whats-new (@tgorkin )
- [ ] Verify upgrade-guide (@Pessimistress  )
- [x] Verify all issues in milestone are closed or move out (@tgorkin )
- [ ] Verify all API changes are documented (@Pessimistress )
- [ ] Website (docs and example) testing: [staging](https://tsherif.github.io/luma.gl/#/)
    - [ ] Testing on Chrome (@ajduberstein)
    - [x] Testing on Safari (@jianhuang01)
    - [x] Testing on Firefox (@1chandu)
    - [x] Testing on Edge + IE11 (@tsherif)
    - [ ] Testing on iOS (@Pessimistress )
    - [ ] Testing on Android (@Pessimistress)
- [x] Cut 7.2-release branch after all fixes
- [x] Update website doc urls to point to `7-2-release` branch (@1chandu)
- [x] Publish 7.2 prod version.

Testing procedure
- access staged doc website
- go through all examples
- verify functionality in control panels
- look for console errors/warnings
- add results of testing as comments on this issue

**Comment by tsherif** [comment]
Edge: 👍 
IE: Broken in all the same ways

**Comment by tgorkin** [comment]
- [ ] Version 7.2 needs to be added to version section https://tsherif.github.io/luma.gl/#/documentation/overview/introduction

**Comment by 1chandu** [comment]
Firefox:

- [ ] Core example TransformFeedback crashes
- [ ] Core example Transform crashes

**Comment by jianhuang01** [comment]
Safari: 👍

**Comment by 1chandu** [comment]
7.2 is released, if any remaining issues should be tracked separately.
