### ISSUE TITLE
7.3 Release Tracker

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#1239]
- [x] Bump all dependencies (math.gl, probe.gl and loaders.gl) to latest release (@1chandu)
- [x] Publish alpha/beta  (@1chandu)
- [x] Bump all examples to latest alpha/beta (@1chandu)
- [x] Stage the website (@tsherif)
- [x] Verify whats-new (@tgorkin )
- [x] Verify upgrade-guide (@Pessimistress  )
- [x] Verify all issues in milestone are closed or move out (@tgorkin )
- [x] Verify all API changes are documented (@Pessimistress )
- [x] Website (docs and example) testing: [staging](https://tsherif.github.io/luma.gl/)
    - [x] Testing on Chrome (@ajduberstein)
    - [x] Testing on Safari (@xintongxia)
    - [x] Testing on Firefox (@1chandu)
    - [x] Testing on Edge + IE11 (@tsherif)
    - [x] Testing on iOS (@Pessimistress )
    - [x] Testing on Android (@Pessimistress)
- [x] Cut 7.3-release branch after all fixes
- [x] Update website doc urls to point to `7-3-release` branch (@1chandu)
- [x] Publish 7.3 prod version.

Testing procedure
- access staged doc website
- go through all examples
- verify functionality in control panels
- look for console errors/warnings
- add results of testing as comments on this issue

**Comment by tsherif** [comment]
General website issues:
- Direct navigation doesn't work for the following pages:
  - [ } https://tsherif.github.io/luma.gl/docs/whats-new
  - [ ] https://tsherif.github.io/luma.gl/docs/upgrade-guide
  - [ ] https://tsherif.github.io/luma.gl/docs/get-started/examples
  - [ ] https://tsherif.github.io/luma.gl/docs/developer-guide/shadertools/shader-assembly
(Seems like it's anything that's not the first item in a menu?)

Edge testing:
- [ ] Header menu items off screen
![luma-edge-header](https://user-images.githubusercontent.com/476017/65431759-fa6ad500-dde7-11e9-8dbe-863af4094348.PNG)
- [ ] Header lags behind scroll
- [ ] Example canvases continually expand
- [ ] Documentation menu jumps back to top after selection
- [ ] Example menu jumps back to top after selection

**Comment by tsherif** [comment]
IE testing:
- [ ] Doesn't load. `fetch is undefined`. Culprit appears to be this line: https://github.com/uber-web/ocular/blob/9ae5825975d41055e09622e36a3e24e9e365a73a/modules/gatsby/src/components/github/github-stars.jsx#L22

**Comment by ibgreen** [comment]
There are plenty of polyfills for fetch. Let's report this on ocular, it should be a quick fix.

**Comment by 1chandu** [comment]
Firfox : all good except 
- [ ] several warnings like :
```
Missing content for entry 0 in chapter Examples 
Object { title: "Examples", entries: (30) […] }
Missing content for entry 1 in chapter Examples 
Object { title: "Examples", entries: (30) […] }
```

**Comment by ibgreen** [comment]
>  several warnings like :

@jckr There are so many of these "spurious warnings", should we comment them out, or be more clear about what actions needs to be taken?
