### ISSUE TITLE
Code cleanup (Refactor phase 1) Tracker

### ISSUE THREAD

**Issue by tsherif** [uber/luma.gl#1272]
Items from the [RFC](https://github.com/uber/luma.gl/blob/master/dev-docs/RFCs/v8.0/luma-refactor.md)
- [x] Consolidate [BaseModel](https://github.com/uber/luma.gl/blob/7.2-release/modules/core/src/lib/base-model.js) and [Model](https://github.com/uber/luma.gl/blob/7.2-release/modules/core/src/lib/model.js)
- [x] Scenegraph cleanup. Remove [CameraNode](https://github.com/uber/luma.gl/blob/7.2-release/modules/core/src/scenegraph/nodes/camera-node.js). Consider whether ModelNode is necessary.
- [x] [Uniform animations](https://github.com/uber/luma.gl/blob/7.2-release/modules/core/src/lib/base-model.js#L280-L333) - Complex, unused, and the `_extractAnimatedUniforms` method appears as 12th most costly function in the [deck.gl stress test](https://github.com/uber/deck.gl/tree/master/test/apps/stress-tests) CPU profile without there being any animated uniforms in the test scene.
- [x] [ShaderCache](https://github.com/uber/luma.gl/blob/7.2-release/modules/core/src/lib/shader-cache.js) - Superseded by `ProgramManager`
- [x] [core/lighting](https://github.com/uber/luma.gl/blob/7.2-release/modules/core/src/lighting/light-source.js), [core/materials](https://github.com/uber/luma.gl/tree/7.2-release/modules/core/src/materials) - currently empty or simple data classes
- [x] [core/multipass](https://github.com/uber/luma.gl/tree/7.2-release/modules/core/src/multipass) - Appears unused (has it been superseded by deck effects?)
- [x] [seer integration](https://github.com/uber/luma.gl/blob/7.2-release/modules/core/src/debug/seer-integration.js) - Complex and will interfere with other parts of the system if enabled (e.g. [GPU timing](https://github.com/uber/luma.gl/blob/7.2-release/modules/core/src/lib/base-model.js#L337-L376)). The `getOverrides` function appears as 6th most costly function in the [deck.gl stress test](https://github.com/uber/deck.gl/tree/master/test/apps/stress-tests) CPU profile without seer being active.
- [x] [debug/parameter-definitions](https://github.com/uber/luma.gl/blob/7.2-release/modules/debug/src/webgl-api-tracing/parameter-definitions.js) - Appears unused
- [x] [main module](https://github.com/uber/luma.gl/tree/7.2-release/modules/main) - Appears unused
- [ ] [core/geometry](https://github.com/uber/luma.gl/tree/7.2-release/modules/core/src/geometries) - Perhaps better suited to math.gl?
- [ ] Unused WebGL classes, e.g. Texture3D, UniformBufferLayout
