### ISSUE TITLE
8.0 Release Tracker

### ISSUE THREAD

**Issue by tsherif** [uber/luma.gl#1307]
- Update docs:
  - New tutorials:
    - [x] Transform Feedback
    - [x] Using an external context
  - Developer guide
    - [x] Context creation/instrumentation
- [x] Bump all dependencies (math.gl, probe.gl and loaders.gl) to latest release (@tsherif)
- [x] Publish alpha/beta  (@tsherif)
- [x] Bump all examples to latest alpha/beta (@tsherif)
- [x] Stage the website (@tsherif)
- [x] Verify whats-new (@tsherif)
- [x] Verify upgrade-guide (@tsherif)
- [x] Verify all issues in milestone are closed or move out (@tsherif)
- [x] Verify all API changes are documented (@tsherif)
- [ ] Website (docs and example) testing: [staging](https://tsherif.github.io/luma.gl/)
    - [x] Testing on Chrome (@tsherif)
    - [x] Testing on Safari (@tsherif)
    - [x] Testing on Firefox (@1chandu)
    - [x] Testing on Edge + IE11 (@tsherif)
    - [x] Testing on iOS (@tsherif)
    - [ ] Testing on Android (@Pessimistress)
- [x] Cut 8.0-release branch after all fixes (@tsherif)
- [x] Update website doc urls to point to `8.0-release` branch (@tsherif)
- [ ] Publish 8.0 prod version.

Testing procedure
- access staged doc website
- go through all examples
- verify functionality in control panels
- look for console errors/warnings
- add results of testing as comments on this issue

**Comment by tsherif** [comment]
All examples render fine in Chrome.

The doc table of contents is having issues. Some entries aren't appearing.

<img width="312" alt="Screen Shot 2019-12-04 at 8 58 42 PM" src="https://user-images.githubusercontent.com/476017/70197162-ec371000-16d8-11ea-8853-3662d45f853b.png">

It seems to be only README.md files that are missing? The pages themselves are actually accessible if you navigate to them directly, e.g.: https://tsherif.github.io/luma.gl/docs/get-started

Any thoughts @jckr?

**Comment by tsherif** [comment]
- [ ] Cross-doc links not working, e.g. `ProgramManager` link here: https://tsherif.github.io/luma.gl/docs/whats-new

**Comment by 1chandu** [comment]
Firefox Testing
- Examples are good
- [ ] Docs
  - [ ] Link  to ProgramManger in whats-new page not working.
  - [ ] Click on any URL from a doc page, and got back to previous page, the menu doesn't load
  - [ ] May links from Tutorials sections are not working too.

**Comment by tsherif** [comment]
Edge:
- [ ] No message for WebGL 2-only examples
- [ ] Can't scroll all the the way to bottom of examples menu (all browsers)

**Comment by tsherif** [comment]
IE
- [ ] Hello instancing mid and high examples rendering incorrectly.
- [ ] Hello instancing low example crashes page `Unable to get property 'luma' of undefined or null reference`

**Comment by tsherif** [comment]
- [ ] GLTF example is rendering black (cross browser)

![image](https://user-images.githubusercontent.com/476017/71120763-12fe4780-21ab-11ea-9ce8-24cb0126ba07.png)

**Comment by ibgreen** [comment]
@tsherif At first blush, this looks like the IBL (Image Based Lighting) is broken, maybe the mip mapped cube texture is not loading properly?

The new `loadImageCube` method in loaders.gl 2.0 was designed to handle this in a clean way, and also the bug you reported around `setUrlPrefix` not being handled by `@loaders.gl/images` is being worked on, one prep PR landed today.

@georgios-uber
