### ISSUE TITLE
8.1 Release Tracker

### ISSUE THREAD

**Issue by tsherif** [uber/luma.gl#1364]
- [x] Bump all dependencies (math.gl, probe.gl and loaders.gl) to latest release (@tsherif)
- [x] Publish alpha/beta  (@tsherif)
- [x] Bump all examples to latest alpha/beta (@tsherif)
- [x] Stage the website (@tsherif)
- [x] Verify whats-new (@tsherif)
- [x] Verify upgrade-guide (@tsherif)
- [x] Verify all issues in milestone are closed or move out (@tsherif)
- [x] Verify all API changes are documented (@tsherif)
- [x] Website (docs and example) testing: [staging](https://tsherif.github.io/luma.gl/)
    - [x] Testing on Chrome (@tsherif)
    - [x] Testing on Safari (@tsherif)
    - [x] Testing on Firefox (@tsherif)
    - [x] Testing on Edge + IE11 (@tsherif)
    - [x] Testing on iOS (@tsherif)
    - [x] Testing on Android (@twojtasz)
- [x] Cut 8.1-release branch after all fixes (@tsherif)
- [x] Update website doc urls to point to `8.1-release` branch (@tsherif)
- [x] Publish 8.1 prod version (@tsherif)

Testing procedure
- access staged doc website
- go through all examples
- verify functionality in control panels
- look for console errors/warnings
- add results of testing as comments on this issue
