### ISSUE TITLE
luma.gl v4.0 Release Tracker

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#167]
# Current plans for luma.gl v4.0

### WebGL2 support
- [x] Add new WebGL2 classes
- [x] Add WebGL2 features to existing classes
- [x] Add docs
- [x] Add test cases

## GL state management
- [x] Scaffold new state manager
- [x] Make state manager handling framebuffer bindings
- [x] Build state management into render calls

### Documentation Overhaul
- [x] All classes documented in markdown
- [x] Examples ported to ES6

### Polish
- [x] Coverage/Coveralls badge

**Comment by 1chandu** [comment]
Closing, but individual tasks remain marked with 4.0 milestone
