### ISSUE TITLE
Transform : Issue tracker for official release

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#576]
#### Background 
List of remaining issues to be addressed before we make this class official
  - [x] Separate double buffering (code wise and API wise) to clarify what the class does.

- [X] [Not valid] If destinationBuffers is not provided, Transform generates a buffer using the source buffer layout. This does not account for source buffers that are not Buffer objects (e.g. generic attribute).
- [x] If elementCount is changed via update, the automatically generated destination buffers are not resized => destination buffers are always re-sized to corresponding source buffers.
- [x] Update the docs : sourceBuffers can be either `Buffer` or `Attribute` instances.

### Previous Issues (to be reconfirmed)

- [x]  Avoid parsing the shader in `Transform` class for version string.
  - [x] Add a getter to `Shader` class to return version information.
  - [x] In `Transform` class build `Shader` object for `vs` if not provided, and based on its `version` pick a prebuilt passthrough `fs`.
  - [x] When `sourceDestinationMap` is provided deduce `varyings` from it.

#### To Do List 
  - [x] Add label and assign to milestone 
  - [x] Coding
  - [x] Doc update
  - [x] Whats new update 
  - [x] Test
