### ISSUE TITLE
6.2 release checklist

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#688]
Moving to 6.2 to address any remaining (un-checked issues here).

## Code

Close all milestone issues https://github.com/uber/luma.gl/milestone/21

## Website (move to ocular)

- [ ] Check pages in website, that layout is readable, skip through all pages
   - [ ] luma.gl title overlaps with sub title in front page
- [ ] Check links in website
- [ ] Add links to old versions of docs (like deck.gl has)
- [ ] Update website links to 6.2-release
- [x] Fix InfoPanel for examples in new ocular website (@jckr #583) (@ibgreen)
- [x] Transform demo is not linked in website. (Ravi)

## Tests

- [x] Test bundling / tree shaking in production app - layer-browser (@ibgreen)

Auto zoom is only affecting Safari/Edge (may be IE too?) but runs fine on Chrome.

For #607 

- [ ] Test luma.gl (Xiaokai)
  - [ ] Chrome:
    - [ ] View code box missing
    - [ ] Object zooms in but not zooms out once the window size changes
    - [ ] Core examples:
      - [ ]  Transform example missing
    - [ ] WEBGL lessons:
      - [ ] Lesson 06 - Texture Filters not working
      - [ ] Lesson 09 - very slow
      - [ ] Lesson 14, 15 not working
      - [ ] Lesson 16: super big image
  - [ ] Safari: 
    - [ ] Automatic zoom in
    - [ ] Core Examples:
        - [ ] Transform Feedback example not working
        - [ ] Transform example missing
    - [ ] WebGL Lessons:
        - [ ] Lesson 1 and 2 not working
        - [ ] Lesson 14, 15 not working
  - [ ] Firefox:
    - [ ] Automatic zoom in
    - [ ] WEBGL lesson
      - [ ] Lesson 14, 15 not working
  - [ ] Linux:
    - [ ] View code box missing
    - [ ] Core Examples:
      - [ ] Cubemap not working
  - [ ] IE:
    - [ ] Examples not show up
    - [ ] The layout of icons in the overview page is disorganized:
<img width="473" alt="luma_gl_overview" src="https://user-images.githubusercontent.com/42359372/44868432-a4a51700-ac3f-11e8-9533-ef67f9d72045.PNG">

- [ ] Test deck.gl (Xiaokai)
  - [ ] Chrome:
    - [ ] lineLayer: Stroke width slider not working
  - [ ] Safari:
    - [ ] lineLayer: Stroke width slider not working
  - [ ] Firefox:
    - [ ] LineLayer: Stroke Width slider not working
  - [ ] Linux:
    - [ ] Very slow
    - [ ] LineLayer: Stroke Width slider not working
    - [ ] GeoJsonLayer(Polygon): legend not working
    - [ ] GeoJsonLayer(Paths): not loading
  - [ ] IE:
    - [ ] Not working

- [ ] Test examples on Edge (Ravi)
     When tested Website-old locally only one below issue
      - [ ] Instancing demo crashes (JS Error)
     Testing using BrowserStack on Mac 
     - [ ] Automatic zoom on almost all showcases and lessons
     - [ ] Instancing demo (JavaScript error)
     - [ ] Transform Feedback (WebGL2) not working
     - [ ] Transform (WebGL2) not working
     - [ ] Lesson 01 and 02 crashed once the window size is adjusted
![screenshot 16](https://user-images.githubusercontent.com/9502731/44755302-6e9a5280-aada-11e8-9c2a-3167591db430.png)

     - [ ] Lesson-6 (texture filters) does not render anything.
![screenshot 17](https://user-images.githubusercontent.com/9502731/44755263-44489500-aada-11e8-99c0-0494c8001cb7.png)

     - [ ] Lesson-14 (Specular highlights) & 15 crash (Java Script error)
![screenshot 19](https://user-images.githubusercontent.com/9502731/44755277-5296b100-aada-11e8-991a-712d320b667d.png)

     deck.gl
     - [ ] LineLayer: the stroke width does not work
     - [ ] UI issue: legend or slider do not display correctly in the following examples(HexagonLayer, GeoJsonLayer, ArcLayer, Trip Routes)

**Comment by jianhuang01** [comment]
duplicated with https://github.com/uber/luma.gl/issues/710
