### ISSUE TITLE
6.2 CHECKLIST

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#710]
## Code

Close all milestone issues https://github.com/uber/luma.gl/milestone/23

## Normal Per-Release WebSite Updates
- [x] revert back to non-ocular website.
- [x] Check links in website
- [ ] Add links to old versions of docs (like deck.gl has)
- [x] Update website links to 6.2-release

## Cross Platform Testing

- [ ] Test luma.gl
  - [x] Chrome (Ravi)
  - [x] Warnings when browsing docs
Cannot find linked doc:  docs/api-reference/shadertools/shadertools-picking.md
Cannot find linked doc:  docs/api-reference/webgl/context-state/with-parameters.md          
    - [x] Core examples:
      - [x]  Transform example missing
    - [x] WEBGL lessons:
      - [x] warnings/reports for lesson 8, 10, 14 and 16 => happens only on visproto, no warnings when hosted on public github page.
[Report Only] Refused to connect to 'https://raw.githubusercontent.com/uber/luma.gl/6.2-release/examples/lessons/10/world.txt' because it violates the following Content Security Policy directive: "connect-src 'self' https://events.uber.com".
      - [x] Lesson 06 - Texture Filters not working -> filtering changes, but hardly noticeable.
      - [x] Lesson 08 - Incorrect lighting (New: 6.2.0-alpha.1, is this a regression from 6.1.0?) => looks correct compared with 6.1 and 6.2 builds.
      - [x] Lesson 09 - very slow
      - [x] Lesson 14, 15 not working
      - [x] Lesson 16: super big image
  - [x] Safari: (Ravi)
    - [x] Core Examples:
        - [x] Transform Feedback example not working
        - [x] Transform example missing
    - [x] WebGL Lessons:
        - [x] Lesson 1 and 2 not working
        - [x] Lesson 14, 15 not working
  - [x] Firefox:
    - [x] WEBGL lesson
      - [x] Lesson 14, 15 not working
  - [ ] Linux:
    - [ ] View code box missing
    - [ ] Core Examples:
      - [ ] Cubemap not working
  - [ ] IE:
    - [ ] Examples not show up
    - [ ] The layout of icons in the overview page is disorganized:
<img width="473" alt="luma_gl_overview" src="https://user-images.githubusercontent.com/42359372/44868432-a4a51700-ac3f-11e8-9533-ef67f9d72045.PNG">

- [x] Test examples on Edge
     When tested Website-old locally only one below issue
      - [ ] Instancing demo crashes (JS Error)
     Testing using BrowserStack on Mac 
     - [ ] Automatic zoom on almost all showcases and lessons
     - [ ] Instancing demo (JavaScript error)
![screenshot 16](https://user-images.githubusercontent.com/9502731/44755302-6e9a5280-aada-11e8-9c2a-3167591db430.png)

     - [ ] Lesson-6 (texture filters) does not render anything.
![screenshot 17](https://user-images.githubusercontent.com/9502731/44755263-44489500-aada-11e8-99c0-0494c8001cb7.png)

     - [ ] Lesson-14 (Specular highlights) & 15 crash (Java Script error)
![screenshot 19](https://user-images.githubusercontent.com/9502731/44755277-5296b100-aada-11e8-991a-712d320b667d.png)

**Comment by ibgreen** [comment]
@jianhuang01 Both of these checklist tickets are closed but both contain many unresolved items?

**Comment by 1chandu** [comment]
Closing, unresolved items in above list are tracked in #756
