### ISSUE TITLE
Tracker: Module Structure

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#724]
# RFC #725 

#### Background 

luma.gl is growing. We need to keep refining it as a collection of separate smaller modules to clarify structure and enable feature selection and composition.

### v7.1
- [x] Break out `@luma.gl/webgl`
- [x] Test Improvements - Alias system hides module dependency errors

### v7.0
- [ ] Whats new update
- [ ] Doc update
- [x] Move misc effects to glfx as experimental.
- [x] Remove `@luma.gl/postprocessing`
- [x] Publish README.md with each module #770
- [x] Start publishing `babel-plugin-inline-constants` #891 
- [x] Start publishing `babel-plugin-strip-comments`
- [x] Remove IO functions from @deck.gl/test-utils #821 (@jianh)
- [x] Remove `@luma.gl/io` (consolidate with loaders.gl) #890
- [x] Separate `luma.gl` and `@luma.gl/core` #889
- [x] Break out `@luma.gl/webgl-state-tracker` #888
- [x] Break out `@luma.gl/webgl2-polyfills` #883 
- [x] Break out `@luma.gl/shadertools`
- [x] Break out `@luma.gl/constants`

### v6.3
- [x] Lerna introduction #721 
- [x] Break out `@luma.gl/debug`
- [x] Break out `@luma.gl/glfx`

**Comment by tsherif** [comment]
@ibgreen @Pessimistress can we call this done?

**Comment by ibgreen** [comment]
We haven't finished documenting this
