### ISSUE TITLE
6.3 CHECKLIST

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#775]
- [x] Verify whats-new (Xiaoji)
- [x] Verify upgrade-guide (Xiaoji)
- [x] Verify all 6.3 issues are closed or move out. (Ravi)
- [ ] Documentations for new submodules (Xiaoji)
- [x] Fix #780
- [ ] Website (docs and example) testing :
    - [ ] Applicable to all browsers
       - [x] lessons/03 fails, models don't rotate.
       - [ ] "ShaderTools" list is messed with other items under "Developer Guide" on document page. This is a common issue on all the platforms
    - [x] Testing on Chrome (Ravi)
    - [x] Testing on Safari (Ravi)
    - [x] Testing on Firefox (Jian)
    - [x] Testing on Edge (Xiaokai) (Ignore any known UI specific issues that we found in earlier release testing)
		- the examples requiring WebGL2 support do not display. Other examples work well

**Comment by jianhuang01** [comment]
- []"ShaderTools" list is messed with other items under "Developer Guide" on document page.
