### ISSUE TITLE
v6.4 release tracker

### ISSUE THREAD

**Issue by Pessimistress** [uber/luma.gl#862]
- [x] Cut release branch
- [x] Update documentation links
- [x] What's New / Upgrade Guide
- Website testing:

  - [x] Windows/IE11
http://pessimistress.github.io/luma.gl/#/ doesn't load, invalid character in bundle.js error in console
  - [x] Windows/Edge
  - [x] Chrome
         - what's new is not updated
         - Examples lesson 08, 14, 15, 16 are down
  - [x] Firefox
		 - Lessons 08, 14, 15, 16 not working
  - [x] Safari
         - what's new is not updated
         - Examples lesson 08, 14, 15, 16 are down
  - [x] Mobile/iOS
  - [x] Mobile/Android
