### ISSUE TITLE
Tracker: Accessor API improvements and alignment

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#871]
### Background 

Specification of attribute accessor props is central to WebGL and the luma.gl API. Multiple similar yet slightly different solutions are in play (Buffer/Accessor/Attribute/...) which neither helps the end-user nor the maintainers. The following sub-tasks are intended to improve alignment.

### v7.0

- [ ] Align `Attribute` with `Accessor` - Issue #653 PR1 #870
- [x] Allow `Accessors` to refer to `Buffer`s (for "interleaving") - PR #869
- [x] Improve accessor/attribute docs - PR1 #868 #869

### v7.x Ideas

- [x] Allow Accessors to refer to a constant value? (Could let us simplify `Attribute`)
- [ ] Don't auto infer type in `Buffer.setData` - or optionally do it only if user supplies `type: 'auto'`?
- [x] Don't create/store an `accessor` on `Buffer` unless explicitly requested by user. E.g.  by providing one of `props.accessor`, `props.type: auto`, ...

**Comment by tsherif** [comment]
@ibgreen Do you still want this open? Feel like some of these don't apply anymore.

**Comment by ibgreen** [comment]
We got most of these, and the attribute class was moved to deck.
