### ISSUE TITLE
Tracker: AnimationLoop changes

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#933]
### TBD
- [ ] make start async?

### v7
- [x] Make `preserveDrawingBuffers` not be turned on by default?
- [x] Fix start/stop creating multiple loops
