### ISSUE TITLE
Tracker: @luma.gl/webgl2-polyfill module

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#969]
This tracks remaining work to make webgl2-polyfill module independently usable:

Docs
- [ ] Whats new update 

- [ ] Tests

Missing:
- [ ] Polyfill constants (e.g. drawbuffer constants)

Refactor:
- [ ] `getParameter` calls on WebGL objects are polyfilled inside luma.gl webgl classes, move to polyfill module.

Cleanup:
- [ ] `polyfillContext` uses a `luma` object on context, remove
- [ ] `polyfillContext` is installed on `global`, remove.

Transpilation:
- [ ] Investigate if GLSL 2 <-> 1 transpiler can be broken out and made part of this module, perhaps as a WebGLShader/WebGLProgram polyfill.

**Comment by tsherif** [comment]
Do you want to make packaging it with the GLSL 3 -> 1 transpiler part of this task?

**Comment by ibgreen** [comment]
> Do you want to make packaging it with the GLSL 3 -> 1 transpiler part of this task?

Yes, that would be very cool! Just need to check that it can be lifted cleanly out of (and plugged back into) shadertools. Added a subtask.

**Comment by tsherif** [comment]
Nice! This is shaping up to be a very cool package!

**Comment by tsherif** [comment]
Refactoring changed direction for 8.0. webgl-polyfill is now part of gltools
