### ISSUE TITLE
7.0 Release Checklist

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#976]
- [x] Remove deprecation warnings in tests and examples

- [x] Verify whats-new (@tgorkin )
- [x] Verify upgrade-guide (@tgorkin )
- [x] Verify all 7.0 issues are closed or move out (@tgorkin )
- [ ] Verify all API changes are documented (@Pessimistress )
- [ ] Website (docs and example) testing: https://tsherif.github.io/luma.gl/#/
    - [ ] Testing on Chrome (@1chandu )
    - [ ] Testing on Safari (@jianhuang01 )
    - [x] Testing on Firefox (@tgorkin )
    - [x] Testing on Edge + IE11 (@tsherif)
    - [x] Testing on iOS (@Pessimistress )
    - [ ] Testing on Android (@Pessimistress)

Testing procedure
- access staged doc website
- go through all examples
- verify functionality in control panels
- look for console errors/warnings
- add results of testing as comments on this issue

**Comment by tsherif** [comment]
Examples break from the website if you return to one a second time.

**Comment by jckr** [comment]
https://github.com/uber-web/ocular/pull/127 was addressing that. I think
deleting /src/components/styled/index.js should be enough, failing that
recopy the file at the same path from ocular-gatsby into the luma.gl/website

**Comment by tsherif** [comment]
@jckr There is no `styled` directory in `components`: https://github.com/uber/luma.gl/tree/master/website/src/components

Is that something we should have?

**Comment by jianhuang01** [comment]
Test with Safari
- [ ] What's new doc has several invalid links printed in console
- [ ] API Reference/API Structure has lots of invalid links printed in console
- [ ] Texture3D example makes the website crash, other examples won't run after this example
- [ ] GLTF example has rendering error
- [ ] In example overview, transform example doesn't have the right link

**Comment by 1chandu** [comment]
Testing on Chrome: (Not including some common issues in above Safari list)
- [ ] Invalid `gifs` on whats-new page.
- [ ] Documentation: Can't select the items on the left panel, especially when bottom items are expanded

**Comment by tsherif** [comment]
Edge
[ ] Stops working after WebGL 2 Example
[ ] Typo in WebGL 2 not supported text
[ ] GLTF example not working

IE
[ ] Instancing header on home page not working
[ ] Examples page a complete mess, images not sized properly
[ ] Cubemap, Shadow map, lesson 4-9, 11-13, 15 examples not working "drawArrays: Insufficient buffer size"
[ ] Instancing, Persistance examples not working "drawArraysInstancedANGLE: Insufficient buffer size" 
[ ] GLTF, lessons 10, 14, 16 examples not working "fetch is undefined"

**Comment by jianhuang01** [comment]
- [ ] Tested with latest staging website in Safari, still stops working after Transform and Texture3D examples. Here is the way to reproduce, 1. click Texture3D or Transform example, 2. click another webgl1 example 3. click Texture3D or Transform example again, get error messages. 4. click webgl1 example stops working

**Comment by tsherif** [comment]
Most IE issues are there in the current website, which looks abysmal in IE and most of the examples don't work. At this point I wonder if it's worth claiming IE support.

The one new thing I don't know how to fix is that importing loaders.gl into the gltf app is preventing the website from loading at all. loaders.gl imports draco3d which has some untranspiled es6 in it that causes a parse error in IE.
